baseURL = "http://awskrug-container-group-www.s3-website.ap-northeast-2.amazonaws.com/"
languageCode = "en-us"
title = "ì»¨í…Œì´ë„ˆ ì†Œëª¨ì„"
theme = "spectre-pixel"
publishDir = "docs"

[params]
  title = "ğŸ³ ì»¨í…Œì´ë„ˆ ì†Œëª¨ì„"
  name = "AWRKRUG container group"
  altName = "ì»¨í…Œì´ë„ˆ ì†Œëª¨ì„"
  description = "í•œêµ­ AWS ì‚¬ìš©ì ëª¨ì„: ì»¨í…Œì´ë„ˆ ì†Œëª¨ì„ ì›¹ì‚¬ì´íŠ¸"
  bio = "ì»¨í…Œì´ë„ˆë¥¼ ë‹¤ë£¨ê³  ìš´ì˜í•˜ëŠ” ê¸°ìˆ ì— ëŒ€í•´ì„œ í•¨ê»˜ í† ë¡ í•˜ê³  ê³µìœ í•˜ëŠ” ì†Œëª¨ì„ì…ë‹ˆë‹¤."
  enableRSS = false

  # Author information in posts
  aboutAuthor = "í•œêµ­ AWS ì‚¬ìš©ì ëª¨ì„: ì»¨í…Œì´ë„ˆ ì†Œëª¨ì„ ìš´ì˜ì§„"

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = [
    "https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css"
  ]
  customJS  = []

  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.

  # Navigation links
	home = ""
	subscribe = ""

	# Pagination links
	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

# Add additional social link entries underneath
[social]
	facebook = "https://www.facebook.com/groups/awskrug/"
	github   = "https://www.github.com/awskrug"

[taxonomies]
  tag = "tags"
